name: Provision Infra with TF
on: 
  workflow_dispatch:
  push:
    branches:
      - rkdemo

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    environment: rkdemo
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Terraform: Init'
        working-directory: ./infra/terraform/
        run: terraform init -backend-config="resource_group_name=${TF_BACKEND_STORAGE_RESOURCE_GROUP_NAME}" -backend-config="storage_account_name=${TF_BACKEND_STORAGE_ACCOUNT_NAME}" -backend-config="container_name=${TF_BACKEND_STORAGE_CONTAINER_NAME}"

      - name: 'Terraform: Plan'
        working-directory: ./infra/terraform/
        run: terraform plan -out tfplan
        
      - name: 'Terraform: Apply'
        working-directory: ./infra/terraform/
        run: terraform apply tfplan